spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  config: classpath:logback-dev.xml

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}/api/v2/spans

admin:
  monitoring:
    kibana-url: ${KIBANA_URL}
  auth:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:change-me}

server:
  forward-headers-strategy: native
